- name: Install app requirements
  hosts: all
  become: true
  tasks:
  - name: Update apt package index
    apt:
      update_cache: true

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Install python pip
    apt:
      name: python-pip
      state: present

  - name: Install additional requirements
    pip:
      name:
        - package1
        - package2
      state: present
